// 설비 객체 에디터 프로젝트 용어집 데이터
// dt-editor-glossary.html 에서 이관 (원문 그대로)

export type GlossaryCatId = 'mfg' | 'dt' | 'stream' | 'std' | 'sw';

export type GlossaryTerm = {
  t: string;        // 용어
  full: string;     // 원어 / 풀네임
  cat: GlossaryCatId;
  d: string;        // 설명
  rel?: string[];   // 연관 정보 (<code>…</code> 인라인 허용)
};

export const GLOSSARY_CAT_ORDER: GlossaryCatId[] = ['mfg', 'dt', 'stream', 'std', 'sw'];

export const GLOSSARY_CATS: Record<GlossaryCatId, { label: string; desc: string }> = {
  mfg:{label:"제조 도메인", desc:"공장 현장·생산관리에서 쓰는 말"},
  dt:{label:"디지털 트윈·3D", desc:"가상 공장·렌더링·동기화"},
  stream:{label:"이벤트·스트리밍", desc:"데이터가 흐르는 방식"},
  std:{label:"산업 표준", desc:"지켜야 할 규약"},
  sw:{label:"SW 아키텍처", desc:"에디터·런타임 설계 개념"}
};

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ---------- 제조 도메인 ----------
  {t:"MES", full:"Manufacturing Execution System", cat:"mfg",
   d:"생산 실행 시스템. 작업 지시를 관리하고 계획을 세우고 실적을 관리한다. 이 프로젝트에서 목표·품목·작업지시 데이터의 출처. 보통 DB를 열어주거나 REST API로 연동한다.",
   rel:["연관: ERP, 작업지시, KPI"]},
  {t:"PLC", full:"Programmable Logic Controller", cat:"mfg",
   d:"설비를 실제로 제어하는 산업용 컨트롤러. 센서·액추에이터를 물고 있고, 여기서 나오는 신호가 엣지 수집의 원천이 된다. Modbus·OPC-UA·Siemens S7 등으로 통신.",
   rel:["연관: SCADA, Modbus, OPC-UA"]},
  {t:"SCADA", full:"Supervisory Control and Data Acquisition", cat:"mfg",
   d:"여러 PLC를 감시·제어하는 상위 시스템. 현장 계층에서 PLC↔SCADA↔MES↔ERP로 데이터가 올라간다. HMI 화면이 대개 SCADA 위에 얹힌다.",
   rel:["연관: PLC, HMI, MES"]},
  {t:"HMI", full:"Human-Machine Interface", cat:"mfg",
   d:"작업자가 설비 상태를 보고 조작하는 화면. 이 에디터가 만드는 3D 트윈도 넓게 보면 차세대 HMI. 색·아이콘 규약(ISA-101)이 여기 적용된다.",
   rel:["연관: SCADA, ISA-101"]},
  {t:"ERP", full:"Enterprise Resource Planning", cat:"mfg",
   d:"전사 자원관리(재무·구매·재고 등). 제조 데이터 흐름의 최상단. MES가 ERP와 현장 사이를 잇는다.",
   rel:["연관: MES"]},
  {t:"KPI", full:"Key Performance Indicator", cat:"mfg",
   d:"핵심 성과 지표. 제조에서는 보통 PQCD로 묶는다 — 생산성(P)·품질(Q)·원가(C)·납기(D). 정부 지원사업은 이 정량 목표 달성을 요구한다.",
   rel:["구성: P·Q·C·D"]},
  {t:"OEE", full:"Overall Equipment Effectiveness", cat:"mfg",
   d:"설비 종합 효율. 가용성 × 성능 × 품질로 계산하는 제조 대표 지표. 다운타임·불량률·사이클타임이 모두 여기로 수렴한다.",
   rel:["연관: 다운타임, 사이클타임, 양품률"]},
  {t:"다운타임", full:"Downtime", cat:"mfg",
   d:"설비 가동이 정지된 시간. 고장·수리 등 예기치 못한 정지는 집계하고, 생산할 게 없어 쉬는 계획 정지는 보통 제외한다. OEE의 가용성을 깎는 요인.",
   rel:["연관: OEE, 가동률"]},
  {t:"사이클 타임", full:"Cycle Time", cat:"mfg",
   d:"제품 1개를 생산하는 데 걸리는 시간. AAS의 Operational Data에 들어가는 대표 값. 상태 그래프에서 '예상 소요시간'으로 쓰여 지연 감지의 기준이 된다.",
   rel:["연관: UPH, Takt Time"]},
  {t:"UPH", full:"Units Per Hour", cat:"mfg",
   d:"시간당 생산 가능 수량. 설비 능력을 나타내는 운영 데이터. 사이클 타임의 역수 개념.",
   rel:["연관: 사이클 타임"]},
  {t:"양품률 / 불량률", full:"Yield / Defect Rate", cat:"mfg",
   d:"전체 중 정상품(양품)과 불량품의 비율. 품질(Q) KPI의 핵심. 이론상 목표는 양품 100%지만 현실적으로 회사별 임의 목표치를 둔다.",
   rel:["연관: KPI, 예지보전"]},
  {t:"품목 / 품목코드", full:"Item / Item Code", cat:"mfg",
   d:"생산 대상 제품. 품목코드 + 품목명으로 식별. MES가 작업지시와 함께 내려준다.",
   rel:["연관: MES, 작업지시"]},
  {t:"작업지시", full:"Work Order", cat:"mfg",
   d:"무엇을 언제 얼마나 만들지 지시. 이 시점에 생산 계획·목표가 확정된다. 공정 조건 최적화 에이전트가 여기에 맞춰 세팅값을 제시한다.",
   rel:["연관: MES, 품목"]},
  {t:"예지보전", full:"Predictive Maintenance (PdM)", cat:"mfg",
   d:"고장이 나기 전에 예측해 정비하는 것. 온도 등 값이 정상 범위를 언제 벗어날지 예측 → 알람. 이상탐지·머신러닝의 대표 응용.",
   rel:["연관: 이상탐지, 예지보전"]},
  {t:"어노테이션", full:"Annotation (labeling)", cat:"mfg",
   d:"이미지·데이터에 '어디가 문제인지, 클래스가 무엇인지' 표시해 학습 데이터를 만드는 작업. YOLO 결함 검출 모델 학습의 전처리 단계.",
   rel:["연관: YOLO, 학습 데이터"]},

  // ---------- 디지털 트윈·3D ----------
  {t:"디지털 트윈", full:"Digital Twin", cat:"dt",
   d:"현실 설비·공장을 가상 공간에 복제해 실시간 동기화하는 것. 현실 로봇이 움직이면 가상 로봇도 같이 움직인다. 이 프로젝트의 최종 산출물.",
   rel:["구성: 데이터 수집 · 매핑 · 3D 표시"]},
  {t:"Unity", full:"게임/3D 엔진", cat:"dt",
   d:"3D 그래픽 엔진. 가볍고 널리 쓰여 웹 3D 구동에 적합. 이 프로젝트의 3D 컨슈머가 Unity 기반. 씬(scene) 안의 오브젝트를 상태 이벤트에 맞춰 애니메이션한다.",
   rel:["연관: WebGL, Scene, GameObject"]},
  {t:"WebGL", full:"Web Graphics Library", cat:"dt",
   d:"브라우저에서 3D를 그리는 웹 표준. Unity에서 WebGL로 빌드(래핑)하면 설치 없이 웹에서 트윈이 돈다. Unity 네이티브보다 가볍다.",
   rel:["연관: Unity, 브라우저 배포"]},
  {t:"Scene / GameObject", full:"씬 / 게임오브젝트", cat:"dt",
   d:"Unity의 3D 공간(Scene)과 그 안의 개별 물체(GameObject). 설비 하나가 GameObject 하나에 대응. Transform 경로로 계층을 이룬다.",
   rel:["주의: 경로를 계약키로 쓰지 말 것"]},
  {t:"Scene Manifest", full:"씬 매니페스트", cat:"dt",
   d:"Unity 빌드 시 추출하는, 씬 안의 노드 목록. 각 노드에 안정적인 sceneNodeId와 지원 역할(supportedRoles)을 담는다. 에디터가 이걸 가져와 역할↔3D를 연결한다.",
   rel:["필드: <code>sceneNodeId</code> <code>supportedRoles</code>"]},
  {t:"visualKey / 애니메이션 키", full:"3D 표현 키", cat:"dt",
   d:"상태·전이에 부여하는 3D 표현 식별자. 컨슈머가 이 키로 오브젝트 외형이나 재생할 애니메이션 클립을 고른다. 상태 그래프에서 지정.",
   rel:["연관: 상태 그래프, Scene"]},
  {t:"오브젝트 키", full:"Object Key", cat:"dt",
   d:"에디터가 내보내는, 3D 오브젝트를 가리키는 키. 현재는 <code>설비code.시나리오key</code>(예: CNV-01.main) 형태. 개선안은 이를 영구 ID 기반으로 바꾸자는 것.",
   rel:["예: <code>CNV-01.main</code>"]},
  {t:"모델링 / CATIA", full:"3D Modeling", cat:"dt",
   d:"설비의 3D 형상을 만드는 작업. CATIA는 기계공학용 대표 CAD 툴. 이 프로젝트의 3D 모델러가 담당하며, 에디터는 완성된 모델을 씬에서 참조한다.",
   rel:["연관: Scene, 3D 모델러"]},
  {t:"이상탐지", full:"Anomaly Detection", cat:"dt",
   d:"정상 범위를 벗어나는 데이터를 찾아내는 것. 하한/상한을 두고 유입 값이 언제 벗어날지 예측. 예지보전의 기반 기술. DataFlow 워크플로우로 구현.",
   rel:["연관: 예지보전, DataFlow"]},

  // ---------- 이벤트·스트리밍 ----------
  {t:"Kafka", full:"Apache Kafka", cat:"stream",
   d:"대용량 메시지 스트리밍 브로커. 생산자(producer)가 토픽에 메시지를 넣으면 소비자(consumer)가 구독해 받는다. 이 프로젝트의 실시간 데이터 중간 계층.",
   rel:["개념: Topic · Producer · Consumer · Partition"]},
  {t:"Topic / Partition", full:"토픽 / 파티션", cat:"stream",
   d:"Kafka에서 메시지를 분류하는 채널(Topic)과, 그것을 병렬 처리하기 위해 쪼갠 단위(Partition). partition key를 어떻게 정하느냐가 순서 보장·부하 분산을 좌우한다.",
   rel:["결정필요: partition key 규칙"]},
  {t:"Producer / Consumer", full:"생산자 / 소비자", cat:"stream",
   d:"Kafka에 메시지를 넣는 쪽(Producer)과 받는 쪽(Consumer). 파이썬 파이프라인이 produce, DT 런타임이 consume. 에디터는 이 경로 바깥에 있어야 한다.",
   rel:["연관: Kafka, 파이프라인"]},
  {t:"CloudEvents", full:"CNCF 이벤트 표준", cat:"stream",
   d:"이벤트 메타데이터를 공통 형식으로 기술하는 CNCF 표준. Kafka 바인딩을 지원하며 id·source·type·subject·time 같은 봉투(envelope)를 제공. 내부 data는 도메인 스키마로 별도 정의한다.",
   rel:["필드: <code>id</code> <code>source</code> <code>type</code> <code>time</code> <code>data</code>"]},
  {t:"AsyncAPI", full:"비동기 API 명세", cat:"stream",
   d:"이벤트 기반 통신의 계약을 문서화하는 표준(REST의 OpenAPI에 대응). Kafka 메시지와 Schema Registry를 함께 표현. Runtime Event Contract 문서화에 적합.",
   rel:["대응: OpenAPI(동기) ↔ AsyncAPI(비동기)"]},
  {t:"Schema Registry", full:"스키마 레지스트리", cat:"stream",
   d:"메시지 스키마를 중앙에서 버전 관리하는 저장소. 생산자·소비자가 같은 구조를 쓰도록 강제하고, 호환성 규칙(하위호환 등)을 검증한다.",
   rel:["연관: Kafka, AsyncAPI"]},
  {t:"REST API", full:"Representational State Transfer", cat:"stream",
   d:"HTTP 기반 요청-응답 API. 요청하면 결과를 준다(동기). DataFlow가 REST로 분석 결과를 내보내고, MES 연동도 REST를 쓴다. 실시간 스트림엔 부적합.",
   rel:["연관: FastAPI, MES 연동"]},
  {t:"WebSocket", full:"양방향 실시간 연결", cat:"stream",
   d:"브라우저와 서버 간 지속 연결로 양방향 실시간 통신. 브라우저 WebGL은 Kafka를 직접 못 물기 때문에, 보통 Kafka → Runtime Adapter → WebSocket → Unity WebGL로 잇는다.",
   rel:["경로: Kafka → Adapter → WebSocket → Unity"]},
  {t:"gRPC-Web / SSE", full:"대체 실시간 전송", cat:"stream",
   d:"브라우저 실시간 전송의 다른 선택지. SSE(Server-Sent Events)는 서버→브라우저 단방향, gRPC-Web은 구조화된 RPC. WebSocket과 함께 후보군.",
   rel:["연관: WebSocket, 3D 브릿지"]},
  {t:"품질 코드(Quality)", full:"Data Quality Code", cat:"stream",
   d:"값이 얼마나 믿을 만한지 나타내는 코드. GOOD·UNCERTAIN·BAD·STALE·DISCONNECTED·CONFIG_ERROR 등. 현재값만 저장하면 '정지'와 '통신두절'을 구분 못 하므로 필수.",
   rel:["값: GOOD · STALE · DISCONNECTED …"]},
  {t:"타임스탬프(Source vs Ingest)", full:"발생 시각 vs 수집 시각", cat:"stream",
   d:"sourceTimestamp(현장에서 값이 발생한 시각)와 ingestedAt(시스템이 받은 시각)을 구분. 지연·순서 뒤집힘을 판단하려면 둘 다 필요하다.",
   rel:["필드: <code>sourceTimestamp</code> <code>ingestedAt</code>"]},

  // ---------- 산업 표준 ----------
  {t:"AAS", full:"Asset Administration Shell", cat:"std",
   d:"자산(설비)을 표준화해 관리하는 국제 표준. 시맨틱 상호운용이 목적 — '온도'의 의미를 국제적으로 통용되게 한다. 설비=Asset, 기능적 측면=Submodel 구조. IDTA가 공식 템플릿 제공.",
   rel:["구조: Asset → Submodel"]},
  {t:"Submodel", full:"AAS 서브모델", cat:"std",
   d:"AAS에서 자산의 한 측면을 기술하는 단위. 표준 공통 3종: Nameplate(명판)·Technical Data(기술)·Operational Data(운영). 모든 태그가 Property는 아니다(File·Operation 등도 있음).",
   rel:["종류: Nameplate · Technical · Operational"]},
  {t:"semanticId", full:"시맨틱 ID", cat:"std",
   d:"AAS 요소의 '의미'를 가리키는 전역 식별자(보통 URI). 업체마다 다른 이름을 쓰지 않고 같은 semanticId를 쓰면 국제적으로 같은 뜻이 된다. 표준 역할 사전의 근거.",
   rel:["예: <code>https://.../OperatingSpeed</code>"]},
  {t:"idShort", full:"AAS 요소 이름", cat:"std",
   d:"AAS 요소의 짧은 식별 이름(사람+기계용). 명명 규칙을 따라야 AASX 직렬화·API 내보내기가 된다. 태그 메타데이터에 포함.",
   rel:["연관: AAS, semanticId"]},
  {t:"AASX", full:"AAS 패키지 포맷", cat:"std",
   d:"AAS 모델을 파일로 주고받는 표준 패키지 형식. 정부 사업 검수나 외부 연동 때 이 형식으로 내보낼 수 있어야 한다. AAS 호환 검증의 목표 산출물.",
   rel:["연관: AAS, 내보내기"]},
  {t:"IDTA", full:"Industrial Digital Twin Association", cat:"std",
   d:"AAS 표준을 관리하는 국제 단체. 공식 Submodel Template과 사양을 배포한다. 에디터의 템플릿 카탈로그를 IDTA 기준으로 맞추는 것이 좋다.",
   rel:["연관: AAS, Submodel Template"]},
  {t:"ISA-101", full:"HMI 설계 표준", cat:"std",
   d:"산업 HMI 화면 설계 표준. 핵심은 색 규약 — 정상은 차분하게(저채도), 경고·고장에만 강한 색. 정상 화면이 알록달록하면 진짜 경보가 묻힌다. 고장(적)과 통신두절(회+아이콘)은 구분.",
   rel:["색: 정상 · 경고 · 고장 · 통신두절"]},
  {t:"OPC-UA", full:"OPC Unified Architecture", cat:"std",
   d:"현대 산업 통신 표준. 단순 전송이 아니라 데이터에 구조·타입·의미를 담는 '정보 모델'을 제공하고 보안·벤더 상호운용을 갖췄다. 신규 설비 연결의 선호 프로토콜.",
   rel:["대비: OPC-UA=의미 / MQTT=전송"]},
  {t:"MQTT", full:"메시지 큐 텔레메트리 전송", cat:"std",
   d:"경량 pub/sub 전송 프로토콜. 데이터를 효율적으로 구독자에게 보내는 데 특화. OPC-UA와 경쟁 아님 — OPC-UA는 모델링, MQTT는 이동을 담당(둘을 함께 쓰기도).",
   rel:["대비: MQTT=전송 / OPC-UA=모델"]},
  {t:"Modbus", full:"산업용 시리얼/TCP 프로토콜", cat:"std",
   d:"가장 오래되고 널리 쓰이는 단순 프로토콜. 레지스터와 코일만 다뤄 구조가 빈약하지만 벤더 지원이 광범위해 레거시 설비 연결의 사실상 공용어. Modbus TCP가 이더넷 버전.",
   rel:["연관: PLC, 레거시 설비"]},

  // ---------- SW 아키텍처 ----------
  {t:"상태 기계", full:"State Machine (FSM)", cat:"sw",
   d:"상태와 상태 간 전이(transition)로 동작을 표현하는 모델. 설비의 가동/정지/고장 등을 상태로, 신호 조건을 전이로. 이 에디터의 상태 그래프가 곧 상태 기계 저작기.",
   rel:["구성: State · Transition · Condition"]},
  {t:"Transition / Guard", full:"전이 / 가드 조건", cat:"sw",
   d:"한 상태에서 다른 상태로 넘어가는 것(Transition)과 그 발화 조건(Guard). 트리거 조건(시작)과 완료 조건(도착)은 별개. 조건은 구체 태그가 아니라 역할을 참조.",
   rel:["필드: 트리거·완료·타임아웃"]},
  {t:"우선순위(priority)", full:"전이 우선순위", cat:"sw",
   d:"한 상태에서 여러 전이 조건이 동시에 참일 때 값이 큰 쪽 하나만 발화시키는 장치. 고장을 100처럼 높게 둬 정상 흐름보다 먼저 잡는다. 상태 결정성의 핵심.",
   rel:["예: 고장 100 > 경고 70 > 정상 50"]},
  {t:"디바운스 / 채터링 방지", full:"Debounce", cat:"sw",
   d:"신호가 짧게 떨릴 때(chattering) 오작동을 막는 최소 체류시간. 이 시간이 지나야 나가는 조건을 평가한다. 0이면 즉시 전이.",
   rel:["필드: <code>minimumHoldMs</code> <code>debounceMs</code>"]},
  {t:"결정성(Determinism)", full:"Deterministic Behavior", cat:"sw",
   d:"같은 입력에 항상 같은 결과가 나오는 성질. 상태 기계에서 조건이 겹칠 때 결과가 갈리면 안 된다. 우선순위·평가 순서로 보장. (파일럿이 구형 C# 엔진의 이 결함을 고침.)",
   rel:["연관: 우선순위, 상태 기계"]},
  {t:"불변 ID vs 코드", full:"Immutable ID vs Code", cat:"sw",
   d:"시스템이 참조하는 안 바뀌는 식별자(ID)와 사람이 읽는 이름(code)을 분리하는 원칙. code를 바꿔도 ID로 참조하므로 바인딩이 안 끊긴다. UUIDv7·ULID를 ID로 쓴다.",
   rel:["ID: UUIDv7 / ULID · code: 사람용"]},
  {t:"UUID / ULID", full:"고유 식별자 체계", cat:"sw",
   d:"전역에서 충돌 없는 ID 생성 방식. UUIDv7·ULID는 시간순 정렬이 되는 최신 방식이라 DB 인덱스에 유리. Asset·Tag·StateModel·SceneNode ID로 권장.",
   rel:["연관: 불변 ID"]},
  {t:"역할 키(Role Key)", full:"Role Key", cat:"sw",
   d:"설비 안에서 무엇을 제어/표현하는지 나타내는 키(motion.main, indicator.fault 등). 그래프는 구체 태그가 아니라 역할을 참조하고, 실제 태그는 설비마다 바인딩에서 정해진다.",
   rel:["예: <code>motion.main</code> <code>indicator.run</code>"]},
  {t:"바인딩(Binding)", full:"Binding", cat:"sw",
   d:"추상적 역할과 실제 태그를 연결하는 것. 같은 타입 설비 10대가 서로 다른 태그 주소를 써도 역할 바인딩으로 그래프 하나를 공유. 필수 역할 미바인딩 시 엔진이 설비를 건너뛴다.",
   rel:["연관: 역할 키, 태그"]},
  {t:"Canonical Domain Model", full:"정규 도메인 모델", cat:"sw",
   d:"구형·웹 등 여러 도구가 공유하는 중립 데이터 모델. UI를 합치지 말고 이 모델로 저장소를 통합. 각 도구는 Canonical로 변환해 읽고 쓴다.",
   rel:["연관: 구형·웹 공존, Import"]},
  {t:"Definition vs Runtime Contract", full:"정의 계약 vs 이벤트 계약", cat:"sw",
   d:"거의 안 변하는 정적 정의(에디터가 발행)와 초당 수십 건 흐르는 동적 이벤트(Kafka)를 별개 계약으로 분리. 하나의 거대 JSON으로 합치지 않는다.",
   rel:["A: 정의(정적) / B: 이벤트(동적)"]},
  {t:"모델 버전 4종", full:"schema · model · scene · runtime", cat:"sw",
   d:"섞으면 호환성 판단이 불가능해지는 네 버전. schemaVersion(구조)·modelVersion(정의)·sceneVersion(Unity)·runtimeVersion(컨슈머)을 따로 관리한다.",
   rel:["<code>schema</code> <code>model</code> <code>scene</code> <code>runtime</code>"]},
  {t:"원자적 배포", full:"Atomic Deployment", cat:"sw",
   d:"패키지 전체를 한 번에 활성화(포인터 교체)해 중간의 불완전한 모델을 컨슈머가 읽지 못하게 하는 것. 실패 시 이전 버전으로 롤백. JSON 덮어쓰기는 프로토타입까지만.",
   rel:["연관: 버전, 롤백, Registry"]},
  {t:"Definition Registry", full:"정의 레지스트리", cat:"sw",
   d:"버전이 붙은 불변 모델 패키지를 저장·관리하는 저장소. 어떤 버전이 활성인지 포인터로 관리하고 승인·감사 로그를 남긴다. 에디터와 런타임 사이 계층.",
   rel:["연관: 원자적 배포, 런타임"]},
  {t:"Runtime Adapter", full:"런타임 어댑터", cat:"sw",
   d:"Kafka와 3D 컨슈머 사이에서 모델 해석·상태 평가를 맡는 서버 서비스. Unity는 표현만 하고 계산은 여기서. 상태 엔진을 화면이 아니라 서버에 두는 이유.",
   rel:["경로: Kafka → Adapter → Unity"]},
  {t:"RAG", full:"Retrieval-Augmented Generation", cat:"sw",
   d:"LLM이 자기 지식 대신 회사 내부 문서를 근거로 답하게 하는 기술. 종류: Document·SQL·Vector·Graph RAG. Data Space 프로젝트의 요소 기술.",
   rel:["종류: Document · SQL · Vector · Graph"]},
  {t:"MLOps", full:"Machine Learning Operations", cat:"sw",
   d:"데이터 분석 → 워크플로우 설계 → 학습 → 배포·운영을 관리하는 루프. 순수 개발보다 데이터 사이언티스트 성격. DataFlow가 이 워크플로우를 노드로 구성하는 도구.",
   rel:["연관: DataFlow, 데이터 사이언티스트"]},
  {t:"YOLO", full:"You Only Look Once", cat:"sw",
   d:"실시간 객체 검출 알고리즘. 이미지에서 사람·물체·결함 위치를 한 번에 찾는다. 이 프로젝트에선 이미지 검사(긁힘 등 결함 검출) 모델에 사용.",
   rel:["연관: 어노테이션, 이상탐지"]},
  {t:"DataFlow", full:"내부 제품 · 분석 플랫폼", cat:"sw",
   d:"팀 자체 솔루션. 이상탐지·예측 로직을 노드(함수) 연결 워크플로우로 구성하고, Build하면 REST API 엔드포인트가 생긴다. 외부 시스템은 분석 코드 없이 결과만 받는다.",
   rel:["개념: 노드=함수 · REST 노출"]},
  {t:"Data Space", full:"내부 프로젝트 · 데이터 플랫폼", cat:"sw",
   d:"AI 에이전트들이 쓸 데이터 플랫폼을 만드는 내부 프로젝트(설계 중). DataFlow와 연계하며 RAG 계열 요소 기술이 들어간다.",
   rel:["연관: DataFlow, RAG, AI 에이전트"]},
];
